### PR TITLE
Add basic logging and configuration

### PR DESCRIPTION
**Pull request by jcoffa**

### CODE REVIEW

**Comment by jcoffa** [comment]
The diff is slightly polluted because it also removes trailing whitespace from the entire file. Sorry! 😄

**Comment by jcoffa** [comment]
Implements this feature request from the discord: https://discord.com/channels/1292895470301220894/1300620313461129226

**Comment by mrusse** [comment]
Looks awesome. Going to run for awhile just to make sure there are no issues before merging. 👍

**Comment by mrusse** [comment]
Works great! Tyvm! Only a couple things I noticed. Maybe add default options if no logging options are found in config.ini? I forgot to add them when I tested it and it causes a crash. Other than that maybe change the default level to info instead of debug.

**Comment by mrusse** [comment]
Ty! Merged.

**Pull request merged**
