### PR TITLE
Add search_source option

### PR DESCRIPTION
**Pull request by lvleph**
This PR implements `cutoff_unmet` option. This option will allow soularr to downloads albums with unmet quality cutoff in addition to missing. However, with the current state of the code and the limitation to `pyarr.lidarr.get_wanted` this is an either or option.

### CODE REVIEW

**Comment by mrusse** [comment]
I see many spacing / linting issues in the proposed changes. Also some spelling mistakes in the readme changes.

One actual change I would like is that instead of having a cutoff_unmet = False or True I think the variable should be something like search_source = wanted_l

**Comment by erichlf** [comment]
> I see many spacing / linting issues in the proposed changes. Also some spelling mistakes in the readme changes.
> 
> One actual change I would like is that instead of having a cutoff_unmet = False or True I think the variable should be something like search_source = wanted_list or cutoff_unmet

You don't have anything that sets the code standard, so I have no idea what it should be. I see that my editor settings removed trailing whitespace, which seemed to be a good change so I left it.

I can change the variable name and make it a string.

**Comment by lvleph** [comment]
> I see many spacing / linting issues in the proposed changes. Also some spelling mistakes in the readme changes.
> 
> One actual change I would like is that instead of having a cutoff_unmet = False or True I think the variable should be something like search_source = wanted_list or cutoff_unmet

You don't have anything that sets the code standard, so I have no idea what it should be. I see that my editor settings removed trailing whitespace, which seemed to be a good change so I left it.

I can change the variable name and make it a string.

**Comment by mrusse** [comment]
Looking at it again you are totally right. Seems like the issue is with my linter (more like a lack of linter I guess...). So yeah just the couple other things. But otherwise great changes so thanks again!

**Comment by mrusse** [comment]
Looks great thank you. Merging to dev and will test and add a couple changes of my own before pushing to main and latest docker image.

**Pull request merged**
